### ISSUE TITLE
KeyError during data preprocessing

### ISSUE THREAD

**Issue by noe** [dojoteef/synst#1]
Following the steps to reproduce the experiments, I got this error in the data preprocessing steps:

```
Running torch 1.1.0
Traceback (most recent call last):
  File "main.py", line 93, in <module>
    main()
  File "main.py", line 38, in main
    args.num_devices, shuffle=args.shuffle
  File "/home/usuaris/veu4/noe.casas/synst/data/utils.py", line 102, in get_dataloader
    dataset = config.dataset(config, split=config.split).load()
  File "/home/usuaris/veu4/noe.casas/synst/data/text.py", line 167, in load
    self.preprocess()
  File "/home/usuaris/veu4/noe.casas/synst/data/annotated.py", line 407, in preprocess
    self.preprocess_bpe(split_filename)
  File "/home/usuaris/veu4/noe.casas/synst/data/annotated.py", line 499, in preprocess_bpe
    source_sentence = encode_sentence(source_line)
  File "/home/usuaris/veu4/noe.casas/synst/data/annotated.py", line 490, in encode_sentence
    for token in line.split()
  File "/home/usuaris/veu4/noe.casas/synst/data/annotated.py", line 490, in <genexpr>
    for token in line.split()
KeyError: '
```

The source code is querying the subword vocabulary to encode a sentence assuming the vocabulary cannot contain unknown words.

I made a quick test ky not encoding tokens that are not part of the vocabulary, just to check. This is the patch:

```
diff --git a/data/annotated.py b/data/annotated.py
index 04ebb83..959abc3 100644
--- a/data/annotated.py
+++ b/data/annotated.py
@@ -487,7 +487,7 @@ class AnnotatedTextDataset(TextDataset):
                 sentence = array.array('H')
                 sentence.extend((
                     self.token2id[token]
-                    for token in line.split()
+                    for token in line.split() if token in self.token2id
                 ))

                 byte_rep = sentence.tostring()
```

With this, the preprocessing succeeded, but the later training failed with this error (and I don't know if this is caused by my previous modification):
```
Input Length=(min=1, avg=29, max=479)
Target Length=(min=1, avg=30, max=319)
Train #0 oom=0, nll=0.00(0.00), lr=0, num_tok=0:   0%|                                                                                 | 0/20589 [00:00<?, ?batch/s]Traceback (most recent call last):
  File "main.py", line 93, in <module>
    main()
  File "main.py", line 89, in main
    action(epoch, args.experiment, args.verbose)
  File "/home/usuaris/veu4/noe.casas/synst/actions/train.py", line 274, in __call__
    self.train_epoch(epoch, experiment, verbose)
  File "/home/usuaris/veu4/noe.casas/synst/actions/train.py", line 132, in train_epoch
    for i, batch in enumerate(batches, 1):
  File "/home/usuaris/veu4/noe.casas/miniconda3/envs/synst/lib/python3.6/site-packages/tqdm/_tqdm.py", line 937, in __iter__
    for obj in iterable:
  File "/home/usuaris/veu4/noe.casas/miniconda3/envs/synst/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/usuaris/veu4/noe.casas/miniconda3/envs/synst/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AssertionError: Traceback (most recent call last):
  File "/home/usuaris/veu4/noe.casas/miniconda3/envs/synst/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/usuaris/veu4/noe.casas/miniconda3/envs/synst/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/usuaris/veu4/noe.casas/synst/data/text.py", line 43, in __getitem__
    (i, self.tensorize(i)) for i in index
  File "/home/usuaris/veu4/noe.casas/synst/data/text.py", line 43, in <genexpr>
    (i, self.tensorize(i)) for i in index
  File "/home/usuaris/veu4/noe.casas/synst/data/annotated.py", line 251, in tensorize
    datum['target'], target_annotation, target_spans
  File "/home/usuaris/veu4/noe.casas/synst/data/annotated.py", line 225, in annotated_sequence
    assert not original_target
AssertionError
```

**Comment by dojoteef** [comment]
Hi @noe! I remember you from the conference. I just got back from ACL myself. Hopefully I can help you figure out what's going wrong.

* Question <span>#</span>1: Are you running this in a clean virtual environment with just the requirements needed by the code installed?
* Question <span>#</span>2: have you made any modifications to the code other than the one patch you listed? The patch should not be needed, and in fact should be reverted.

I've verified the code runs correctly by following the instructions I've listed in the README in a fresh virtual environment. That's the reason I ask these questions. In order to better diagnose the problem, can you please provide the output of `pip freeze` and the command line you ran that lead to the error?

**Comment by noe** [comment]
Hi @dojoteef ! As I told you, I like your work a lot, so I tried to run the code while I was still in Florence. Here are the answers:
A1:  Yes, clean virtualenv with python 3.6 created explicitly for this, on an ubuntu 18.04.2, also following the steps from the README file (just cloned the repo, downloaded corenlp, installed virtualenv and ran the preprocessing). Tried with both conda and normal virtualenv, with the same result.
A2: Nope, no modifications, just a clean clone. I started messing around when I got the error.

I tried again from scratch, with the same result. Here's the output of [pip freeze](https://github.com/dojoteef/synst/files/3464433/pipfreeze.txt)

Just in case, the MD5SUM of the WMT data tgz is this:
```
874ab6bbfe9c21ec987ed1b9347f95ec  raw/wmt/wmt_en_de.tar.gz
```

**Comment by noe** [comment]
With Python 3.7.1 I get the same result

**Comment by noe** [comment]
I think the problem may be related to my locale. It seems having LC_ALL and LANG env vars set to en_US.UTF-8 makes the preprocessing work. I will confirm shortly.

**Comment by noe** [comment]
I confirm that the preprocessing error is solved by setting LC_ALL and LANG env vars set to en_US.UTF-8. However, the `AssertionError` in training still happens after that:
```
noe.casas@veuc10:~/synst$ python main.py -b 3175 --dataset wmt_en_de_parsed --span 6 --model parse_transformer -d raw/wmt -p p
reprocessed/wmt -v train --checkpoint-interval 1200 --accumulate 4 --label-smoothing 0
Running torch 1.1.0
Examples=4500966
Vocab Size=37010
Input Length=(min=1, avg=29, max=484)
Target Length=(min=1, avg=30, max=337)
Train #0 oom=0, nll=0.00(0.00), lr=0, num_tok=0:   0%|                                                                                 | 0/20592 [00:00<?, ?batch/s]Traceback (most recent call last):
  File "main.py", line 93, in <module>
    main()
  File "main.py", line 89, in main
    action(epoch, args.experiment, args.verbose)
  File "/home/usuaris/veu4/noe.casas/synst/actions/train.py", line 274, in __call__
    self.train_epoch(epoch, experiment, verbose)
  File "/home/usuaris/veu4/noe.casas/synst/actions/train.py", line 132, in train_epoch
    for i, batch in enumerate(batches, 1):
  File "/home/usuaris/veu4/noe.casas/miniconda3/envs/synst/lib/python3.6/site-packages/tqdm/_tqdm.py", line 937, in __iter__
    for obj in iterable:
  File "/home/usuaris/veu4/noe.casas/miniconda3/envs/synst/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/usuaris/veu4/noe.casas/miniconda3/envs/synst/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AssertionError: Traceback (most recent call last):
  File "/home/usuaris/veu4/noe.casas/miniconda3/envs/synst/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/usuaris/veu4/noe.casas/miniconda3/envs/synst/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/usuaris/veu4/noe.casas/synst/data/text.py", line 43, in __getitem__
    (i, self.tensorize(i)) for i in index
  File "/home/usuaris/veu4/noe.casas/synst/data/text.py", line 43, in <genexpr>
    (i, self.tensorize(i)) for i in index
  File "/home/usuaris/veu4/noe.casas/synst/data/annotated.py", line 251, in tensorize
    datum['target'], target_annotation, target_spans
  File "/home/usuaris/veu4/noe.casas/synst/data/annotated.py", line 225, in annotated_sequence
    assert not original_target
AssertionError
```
(I have `--accumulate 4` because I'm only using 4 GPUs instead of 8)

[These](https://github.com/dojoteef/synst/files/3464758/wmt_md5.txt) are the MD5 hashes of the files in `preprocessed/wmt`

**Comment by dojoteef** [comment]
I'm glad you got part of the issue figured out! Unfortunately, it seems that the preprocessed `.parse` files that you generated are different than [mine](https://github.com/dojoteef/synst/files/3464910/my_wmt_md5.txt). Can you send me a copy of `preprocessed/wmt/newstest2013.tok.en.parse` so I can inspect what's different?

Now I'm starting to wonder if there is some interaction of `LC_ALL` and `LANG` when calling the CoreNLP parsers which is done in [scripts/parse_wrapper.sh](https://github.com/dojoteef/synst/blob/master/scripts/parse_wrapper.sh) and [scripts/parse.sh](https://github.com/dojoteef/synst/blob/master/scripts/parse.sh).

**Comment by noe** [comment]
All the files with `.parse` extension in `preprocessed/wmt/` are empty . I will try to find out why.

**Comment by noe** [comment]
There were two problems: I did not have `jq` installed and the classpath was not properly taken. Now the `.parse` files are being generated correctly.

**Comment by dojoteef** [comment]
Great! I'm glad you figured things out. I'll update the README to include `jq` as a requirement and mention the potential workaround for setting `LC_ALL` and `LANG` if things don't work.
